/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as MyBetsIndexRouteImport } from './../routes/my-bets/index'
import { Route as AuctionsAuctionIdIndexRouteImport } from './../routes/auctions/$auctionId/index'
import { Route as AuctionsAuctionIdBidRouteImport } from './../routes/auctions/$auctionId/bid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBetsIndexRoute = MyBetsIndexRouteImport.update({
  id: '/my-bets/',
  path: '/my-bets/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsAuctionIdIndexRoute = AuctionsAuctionIdIndexRouteImport.update({
  id: '/auctions/$auctionId/',
  path: '/auctions/$auctionId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsAuctionIdBidRoute = AuctionsAuctionIdBidRouteImport.update({
  id: '/auctions/$auctionId/bid',
  path: '/auctions/$auctionId/bid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-bets': typeof MyBetsIndexRoute
  '/auctions/$auctionId/bid': typeof AuctionsAuctionIdBidRoute
  '/auctions/$auctionId/': typeof AuctionsAuctionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-bets': typeof MyBetsIndexRoute
  '/auctions/$auctionId/bid': typeof AuctionsAuctionIdBidRoute
  '/auctions/$auctionId': typeof AuctionsAuctionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/my-bets/': typeof MyBetsIndexRoute
  '/auctions/$auctionId/bid': typeof AuctionsAuctionIdBidRoute
  '/auctions/$auctionId/': typeof AuctionsAuctionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/my-bets' | '/auctions/$auctionId/bid' | '/auctions/$auctionId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/my-bets' | '/auctions/$auctionId/bid' | '/auctions/$auctionId'
  id:
    | '__root__'
    | '/'
    | '/my-bets/'
    | '/auctions/$auctionId/bid'
    | '/auctions/$auctionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyBetsIndexRoute: typeof MyBetsIndexRoute
  AuctionsAuctionIdBidRoute: typeof AuctionsAuctionIdBidRoute
  AuctionsAuctionIdIndexRoute: typeof AuctionsAuctionIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bets/': {
      id: '/my-bets/'
      path: '/my-bets'
      fullPath: '/my-bets'
      preLoaderRoute: typeof MyBetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/$auctionId/': {
      id: '/auctions/$auctionId/'
      path: '/auctions/$auctionId'
      fullPath: '/auctions/$auctionId/'
      preLoaderRoute: typeof AuctionsAuctionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/$auctionId/bid': {
      id: '/auctions/$auctionId/bid'
      path: '/auctions/$auctionId/bid'
      fullPath: '/auctions/$auctionId/bid'
      preLoaderRoute: typeof AuctionsAuctionIdBidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyBetsIndexRoute: MyBetsIndexRoute,
  AuctionsAuctionIdBidRoute: AuctionsAuctionIdBidRoute,
  AuctionsAuctionIdIndexRoute: AuctionsAuctionIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
